export enum EnvEnum {
  POSTGRES__DB_HOST = 'POSTGRES__DB_HOST',
  POSTGRES__DB_USERNAME = 'POSTGRES__DB_USERNAME',
  POSTGRES__DB_PASSWORD = 'POSTGRES__DB_PASSWORD',
  POSTGRES__DB_DATABASE = 'POSTGRES__DB_DATABASE',
  POSTGRES__DB_PORT = 'POSTGRES__DB_PORT',
}
