import { TestManager } from '../../../test-manager.test';
import { UserService } from '../../user.service';
import { faker } from '@faker-js/faker';

/**
 * DOMAIN RULE 07: User ID is automatically generated as UUID and cannot be manually assigned.
 *
 * This test suite verifies that user IDs are automatically generated by the database
 * as UUIDs and cannot be manually assigned during user creation. The ID is managed
 * by the ORM and database layer.
 */
describe('Domain Rule 07 - UUID Auto-Generation', () => {
  beforeAll(async () => {
    await TestManager.beforeAll();
  });

  afterAll(async () => {
    await TestManager.afterAll();
  });

  beforeEach(async () => {
    await TestManager.beforeEach();
  });

  it('07.1 - should not accept manual ID assignment during user creation', async () => {
    const userService = TestManager.getHandler(UserService);

    const user = await userService.createUser({
      username: faker.internet.username(),
      password: faker.internet.password(),
    });

    expect(user.id).toBeDefined();
    expect(typeof user.id).toBe('string');
  });

  it('07.2 - should receive auto-generated UUID after user creation', async () => {
    const userService = TestManager.getHandler(UserService);

    const actualResult = await userService.createUser({
      username: faker.internet.username(),
      password: faker.internet.password(),
    });

    expect(actualResult.id).toBeDefined();
    expect(typeof actualResult.id).toBe('string');
    expect(
      /^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(
        actualResult.id,
      ),
    ).toBe(true);
  });

  it('07.3 - should ensure each user receives a unique ID', async () => {
    const userService = TestManager.getHandler(UserService);

    const result1 = await userService.createUser({
      username: faker.internet.username(),
      password: faker.internet.password(),
    });

    const result2 = await userService.createUser({
      username: faker.internet.username(),
      password: faker.internet.password(),
    });

    expect(result1.id).not.toBe(result2.id);
  });

  it('07.4 - should rely on database/ORM for ID generation', async () => {
    const userService = TestManager.getHandler(UserService);

    const actualResult = await userService.createUser({
      username: faker.internet.username(),
      password: faker.internet.password(),
    });

    expect(actualResult.id).toBeDefined();
    expect(
      /^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(
        actualResult.id,
      ),
    ).toBe(true);
  });

  it('07.5 - should use ID for user identification in all operations', async () => {
    const userService = TestManager.getHandler(UserService);

    const user = await userService.createUser({
      username: faker.internet.username(),
      password: faker.internet.password(),
    });

    const actualResult = await userService.findUserById({ userId: user.id });

    expect(actualResult?.id).toBe(user.id);
  });
});
